# Changes here will be overwritten by Copier
_commit: 971b547
_src_path: gh:34j/pypackage-template
add_me_as_contributor: false
cli_name: distributed-comparison
copyright_year: '2025'
documentation: true
email: 34j.95a2p@simplelogin.com
full_name: 34j
github_app_installation_ids: 31487150,37771054
github_username: 34j
has_cli: true
initial_commit: true
is_django_package: false
open_source_license: MIT
package_name: distributed_comparison
project_name: distributed-comparison
project_short_description: Compare multiple distributed computation frameworks
project_slug: distributed-comparison
run_uv_sync: true
setup_github: true
setup_pre_commit: true

